# Generated by Django 5.1.7 on 2025-03-08 23:28

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_family_member', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('name_of_picture', models.CharField(max_length=255)),
                ('description_of_picture', models.TextField()),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Picture',
                'verbose_name_plural': 'Family Pictures',
                'ordering': ['-created_at'],
            },
        ),
    ]
